# Generated by Django 2.2.14 on 2020-11-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Luxury'), ('SW', 'Casual'), ('OW', 'Dinner Party')], max_length=2),
        ),
    ]
