# Generated by Django 2.2.14 on 2020-11-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201124_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_laterl1',
            new_name='image_lateral1',
        ),
    ]
