# Generated by Django 2.2.14 on 2020-11-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201125_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'Special Offer'), ('S', 'Limited Edition'), ('D', 'New Collection')], max_length=1, null=True),
        ),
    ]
