# Generated by Django 2.2.14 on 2020-12-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201202_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellWIthUsTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stare', models.CharField(blank=True, choices=[('NE', 'Noua cu Etichete'), ('Noua Fara Etichete', 'Noua Fara Etichete'), ('Foarte Buna', 'Foarte Buna'), ('Buna', 'Buna'), ('Purtata', 'Purtata'), ('Prezinta Mici Defecte', 'Prezinta Mici Defecte')], max_length=30, null=True)),
                ('pret', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
